### ISSUE TITLE
clear div sometimes not present

### ISSUE THREAD

**Issue by Aybee** [BugBuster1701/privat-easyupdate3#50]
Hallo Glen,
ich weiß nicht genau wann, aber manchmal wird im BE der DIV zum clearen nicht gerendert. Da ich ein eigenes BE-Theme habe [BackendThemeExtended], fällt das sofort auf. Unten dieser auskommentierte DIV ist es.
```html
<div id="main">
  <h1 class="main_headline">
  <div id="tl_buttons">
  <h2 class="sub_headline">
  <div class="tl_formbody_edit">
  <div class="tl_formbody_edit">
<!-- 
  <div style="clear:both;"></div> 
-->
</div>
```
Das Problem ist, dass du die beiden .tl_formbody_edit floatest, deswegen brauche ich diesen clear. Ein overflow-hidden auf #main würde auch gehen, aber kann sein, dass dann ander Sachen in meinem Theme Ärger machen.

**Comment by BugBuster1701** [comment]
Hmm, diese Zeile ist fest eingebaut und nicht von Bedingungen abhängig. Da müsste dann noch mehr fehlen, also irgendwas abbrechen.
Ich wollte das Teil eh schon mal auf Template umstellen, vielleicht hilft das.

**Comment by Aybee** [comment]
Hier hatte ich von 3.4.5 auf 3.5.2 geupt.
![easyupdate3_-_contao_open_source_cms_3 5_-_2015-10-15_02 56 49](https://cloud.githubusercontent.com/assets/1143013/10502088/a730d646-72e8-11e5-97c1-e938f2ef083f.png)
Und hier von 3.5.3 auf 3.5.4
![easyupdate3_-_contao_open_source_cms_3 5_-_2015-10-15_02 56 08](https://cloud.githubusercontent.com/assets/1143013/10502103/be525cd2-72e8-11e5-94eb-6b9396e3118d.png)
Vergleiche die 3 untersten Zeile.
Das hier ist in Ordnung
![capture_10152015_031034](https://cloud.githubusercontent.com/assets/1143013/10502263/846fb396-72ea-11e5-9529-2b79994040f7.png)
Das hier nicht
![capture_10152015_030557](https://cloud.githubusercontent.com/assets/1143013/10502220/1777b31a-72ea-11e5-9168-a613ad03fb0e.png)
Sehr seltsam. Ob das an geänderten BE-Templates liegt?

**Comment by BugBuster1701** [comment]
Deswegen müssten aber trotzdem die Farben stimmen, die sind ja nicht von den floting abhängig, bzw, das fehlende clear. Kann es sein, dass du keine Hintergundfarbe definiert hast für #main ? Denn daher wird die genommen.

**Comment by Aybee** [comment]
Nein, #main wird nicht ausgedehnt, weil die beiden .tl_formbody_edit gefloatet sind. Es braucht also ein overflow:hidden in #main oder den Clearer.

Die Markierung zeigt #main.
![unbenannt-1](https://cloud.githubusercontent.com/assets/1143013/10511520/0827bbda-733a-11e5-9fa0-78b6de6599ab.png)
Ich teste gerade in meinem Theme, ob das overflow:hidden sonst nirgendwo in die Quere kommt. Habe gerade festgestellt, dass ein float:left auf #main in meinem Theme das #main auch ausdehnt. Im original Contao-Theme ist #main auch float:left, in meinem Theme hatte ich das ausgestellt.

D.h. du müsstest es eigentlich so lassen können, da #main im original Theme auch float:left ist.

**Comment by Aybee** [comment]
Oder du kommst meinem Theme entgegen und gibst diesen beiden .tl_formbody_edit anstatt float:left display:table-cell. Das sieht bei mir genauso aus wie mit float:left, aber #main braucht bei mir dann kein overflow:hidden, oder float:left.

**Comment by BugBuster1701** [comment]
Hmm, probier ich mal aus.

**Comment by Aybee** [comment]
Danke. Und ich teste derweilen, ob mein Theme mit float:left auf #main klar kommt. Es wird sowieso nur ausgeschaltet, wenn die Navigation links fixiert ist, weil ich dann kein float:left brauche, aber es scheint auch **mit** zu funktionieren.

**Comment by BugBuster1701** [comment]
Dann würde ich aber korrekterweise noch ein div mit display:table drum rum bauen müssen, als Einleitung einer Zeile.
```html
<div style="display:table">
	<div class="tl_formbody_edit" style="width: 45%; display: table-cell; border-right: 1px solid;">
	.....
	<div class="tl_formbody_edit" style="width: 45%; display: table-cell;">
</div>
```

**Comment by BugBuster1701** [comment]
Hmm, hab mal ein wenig gespielt mit Firebug. Bei kleinen Auflösungen, das muss ich aber noch einbauen, würde ich dann nur die breite auf auto setzen und das float auf non.
Bei display table-cell müsste ich die Breite auf auto setzen und display von table-cell auf table ändern damit die untereinenader kommen. Ob das so sauber ist? Table Zeile ohne Table Zellen.
Muss ich mir mal in Ruhe anschauen.

**Comment by BugBuster1701** [comment]
@BugBuster1701:  https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/Anzeige/display/Tabelle

**Comment by Aybee** [comment]
Ach, weißte was? Lass es doch einfach so wie es ist. Ich dachte, weil du sowieso dieses <style> im BODY hast, wäre es egal, wenn table und table-row fehlen, solange es funktioniert. Aber ich glaube, <style> im BODY ist ja auch mittlerweile erlaubt.

Noch eine Idee: Was hältst du davon, wenn du das Inline-Style bei den .tl_formbody_edit ganz weglässt. Evtl. dem oberen noch einen Border unten?

Sorry, dass ich dich damit gestört habe, ich denke ich werde mein Theme anpassen.

**Comment by Aybee** [comment]
Ach so, warum war denn eigentlich der Clearer einmal im #main und einmal unter dem #main? Und bei dem STYLE ist es genau umgekehrt.
